pcc:
  url: https://IP:9999
  username: admin
  password: PWD

bare_metal:
  discovery:
    dryRun: false
    parallelism: 50
    discoveryTargets:
      - bmcIpRanges: 10.1.0.1-10.1.0.5
        bmcUser: root
        bmcPassword: root
      - bmcIpRanges: 10.1.0.7
        bmcUser: root
        bmcPassword: toor

  reimage:
    nodes_bmc:
      - 10.1.0.1-10.1.0.5
      - 10.1.0.7
    image: jammy
    locale: en-US
    timezone: PDT
    adminUser: admin
    managed: false
    sshKeys:
      - pcc


  nodes_bmc:
    - 10.1.0.1-10.1.0.5
    - 10.1.0.7
  console: ttyS1
  managed: False
  management_interface:
    subnet: 10.1.1.0/24
    gateway: 10.1.1.254
    properties:
      speed: 1000
      carrierStatus: UP
  node_name_template: g1{int(bmc_ip.split('.')[-1]):03}
  bootable_drive:
    properties:
      TypeLabel: Hardware RAID
