pcc:
  url: https://IP:9999
  username: admin
  password: PWD

custom_action:
  workflow:
    description: action gc test
    nodes_bmc:
      - 10.9.81.105
    pxe: true
    reboot: false
    userActions:
      globalTimeout: 3600000
      actions:
        - name: gc
          image: platina.io/XXXXX:latest
          repository: "platina.io"
          user: "XXXX"
          password: "XXXXX"
          timeout: 3600000
          environment:
            ACTION: diagnostic
      volumes:
        - /dev:/dev
        - /sys:/sys
        - /var/run/docker.sock:/var/run/docker.sock